kind: Namespace
apiVersion: v1
metadata:
  name: jaeger-system

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: jaeger
  namespace: jaeger-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: jaeger-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      serviceAccountName: jaeger
      containers:
        - name: jaeger
          image: jaegertracing/opentelemetry-all-in-one:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-oltp
  namespace: jaeger-system
spec:
  ports:
    - port: 4317
      protocol: TCP
      targetPort: 55680
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-http
  namespace: jaeger-system
spec:
  ports:
    - port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: jaeger
  namespace: jaeger-system
spec:
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  hostnames: ["jaeger.corp.kubehouse.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: jaeger-http
      port: 16686
