
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: default
  namespace: kweb-sso-system
spec:
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  hostnames: ["sso.corp.kubehouse.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kweb-sso
      port: 80
